# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\dev\core\rf_maya\nuTools\util\proxyRigGenerator\ui.ui'
#
# Created: Mon Jul 13 18:02:50 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_proxyRigGenerator_MainWindow(object):
    def setupUi(self, proxyRigGenerator_MainWindow):
        proxyRigGenerator_MainWindow.setObjectName("proxyRigGenerator_MainWindow")
        proxyRigGenerator_MainWindow.resize(380, 300)
        self.centralwidget = QtWidgets.QWidget(proxyRigGenerator_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.proxyCut_tab = QtWidgets.QWidget()
        self.proxyCut_tab.setObjectName("proxyCut_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.proxyCut_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.proxyCut_tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.proxyGeo_lineEdit = QtWidgets.QLineEdit(self.proxyCut_tab)
        self.proxyGeo_lineEdit.setReadOnly(True)
        self.proxyGeo_lineEdit.setObjectName("proxyGeo_lineEdit")
        self.horizontalLayout_3.addWidget(self.proxyGeo_lineEdit)
        self.loadGeo_pushButton = QtWidgets.QPushButton(self.proxyCut_tab)
        self.loadGeo_pushButton.setObjectName("loadGeo_pushButton")
        self.horizontalLayout_3.addWidget(self.loadGeo_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.cutCube_groupBox = QtWidgets.QGroupBox(self.proxyCut_tab)
        self.cutCube_groupBox.setAutoFillBackground(True)
        self.cutCube_groupBox.setFlat(False)
        self.cutCube_groupBox.setObjectName("cutCube_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cutCube_groupBox)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.cutCube_groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.snapCube_pushButton = QtWidgets.QPushButton(self.cutCube_groupBox)
        self.snapCube_pushButton.setObjectName("snapCube_pushButton")
        self.gridLayout.addWidget(self.snapCube_pushButton, 1, 4, 1, 1)
        self.replaceWith_lineEdit = QtWidgets.QLineEdit(self.cutCube_groupBox)
        self.replaceWith_lineEdit.setObjectName("replaceWith_lineEdit")
        self.gridLayout.addWidget(self.replaceWith_lineEdit, 2, 3, 1, 1)
        self.mirrorCube_pushButton = QtWidgets.QPushButton(self.cutCube_groupBox)
        self.mirrorCube_pushButton.setObjectName("mirrorCube_pushButton")
        self.gridLayout.addWidget(self.mirrorCube_pushButton, 2, 4, 1, 1)
        self.jntSuffix_lineEdit = QtWidgets.QLineEdit(self.cutCube_groupBox)
        self.jntSuffix_lineEdit.setObjectName("jntSuffix_lineEdit")
        self.gridLayout.addWidget(self.jntSuffix_lineEdit, 1, 3, 1, 1)
        self.geoSuffix_lineEdit = QtWidgets.QLineEdit(self.cutCube_groupBox)
        self.geoSuffix_lineEdit.setObjectName("geoSuffix_lineEdit")
        self.gridLayout.addWidget(self.geoSuffix_lineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.cutCube_groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.cutCube_groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.cutCube_groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.searchFor_lineEdit = QtWidgets.QLineEdit(self.cutCube_groupBox)
        self.searchFor_lineEdit.setObjectName("searchFor_lineEdit")
        self.gridLayout.addWidget(self.searchFor_lineEdit, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.cutCube_groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.size_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.cutCube_groupBox)
        self.size_doubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.size_doubleSpinBox.setMaximum(100.0)
        self.size_doubleSpinBox.setProperty("value", 1.0)
        self.size_doubleSpinBox.setObjectName("size_doubleSpinBox")
        self.gridLayout.addWidget(self.size_doubleSpinBox, 0, 3, 1, 1)
        self.newCube_pushButton = QtWidgets.QPushButton(self.cutCube_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newCube_pushButton.sizePolicy().hasHeightForWidth())
        self.newCube_pushButton.setSizePolicy(sizePolicy)
        self.newCube_pushButton.setObjectName("newCube_pushButton")
        self.gridLayout.addWidget(self.newCube_pushButton, 0, 4, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.cutCube_groupBox)
        self.groupBox = QtWidgets.QGroupBox(self.proxyCut_tab)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.constraint_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.constraint_radioButton.setChecked(True)
        self.constraint_radioButton.setObjectName("constraint_radioButton")
        self.horizontalLayout_2.addWidget(self.constraint_radioButton)
        self.parent_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.parent_radioButton.setObjectName("parent_radioButton")
        self.horizontalLayout_2.addWidget(self.parent_radioButton)
        self.matrix_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.matrix_radioButton.setObjectName("matrix_radioButton")
        self.horizontalLayout_2.addWidget(self.matrix_radioButton)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.cut_pushButton = QtWidgets.QPushButton(self.proxyCut_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cut_pushButton.sizePolicy().hasHeightForWidth())
        self.cut_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.cut_pushButton.setFont(font)
        self.cut_pushButton.setObjectName("cut_pushButton")
        self.verticalLayout_3.addWidget(self.cut_pushButton)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.setStretch(3, 1)
        self.tabWidget.addTab(self.proxyCut_tab, "")
        self.skinWeights_tab = QtWidgets.QWidget()
        self.skinWeights_tab.setObjectName("skinWeights_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.skinWeights_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.skinWeights_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.skinGeo_lineEdit = QtWidgets.QLineEdit(self.skinWeights_tab)
        self.skinGeo_lineEdit.setReadOnly(True)
        self.skinGeo_lineEdit.setObjectName("skinGeo_lineEdit")
        self.gridLayout_2.addWidget(self.skinGeo_lineEdit, 0, 1, 1, 1)
        self.skinGeo_pushButton = QtWidgets.QPushButton(self.skinWeights_tab)
        self.skinGeo_pushButton.setObjectName("skinGeo_pushButton")
        self.gridLayout_2.addWidget(self.skinGeo_pushButton, 0, 2, 1, 1)
        self.rootJnt_pushButton = QtWidgets.QPushButton(self.skinWeights_tab)
        self.rootJnt_pushButton.setObjectName("rootJnt_pushButton")
        self.gridLayout_2.addWidget(self.rootJnt_pushButton, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.skinWeights_tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.rootJnt_lineEdit = QtWidgets.QLineEdit(self.skinWeights_tab)
        self.rootJnt_lineEdit.setReadOnly(True)
        self.rootJnt_lineEdit.setObjectName("rootJnt_lineEdit")
        self.gridLayout_2.addWidget(self.rootJnt_lineEdit, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.skinWeights_tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.skinGeoSuffix_lineEdit = QtWidgets.QLineEdit(self.skinWeights_tab)
        self.skinGeoSuffix_lineEdit.setObjectName("skinGeoSuffix_lineEdit")
        self.gridLayout_3.addWidget(self.skinGeoSuffix_lineEdit, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.skinWeights_tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.skinJntSuffix_lineEdit = QtWidgets.QLineEdit(self.skinWeights_tab)
        self.skinJntSuffix_lineEdit.setObjectName("skinJntSuffix_lineEdit")
        self.gridLayout_3.addWidget(self.skinJntSuffix_lineEdit, 0, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.generateSkinWeight_pushButton = QtWidgets.QPushButton(self.skinWeights_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.generateSkinWeight_pushButton.setFont(font)
        self.generateSkinWeight_pushButton.setObjectName("generateSkinWeight_pushButton")
        self.verticalLayout_4.addWidget(self.generateSkinWeight_pushButton)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(3, 2)
        self.tabWidget.addTab(self.skinWeights_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        proxyRigGenerator_MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(proxyRigGenerator_MainWindow)
        self.statusBar.setObjectName("statusBar")
        proxyRigGenerator_MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(proxyRigGenerator_MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.skinGeoSuffix_lineEdit, QtCore.SIGNAL("textChanged(QString)"), self.skinJntSuffix_lineEdit.setText)
        QtCore.QObject.connect(self.skinJntSuffix_lineEdit, QtCore.SIGNAL("textChanged(QString)"), self.skinGeoSuffix_lineEdit.setText)
        QtCore.QMetaObject.connectSlotsByName(proxyRigGenerator_MainWindow)

    def retranslateUi(self, proxyRigGenerator_MainWindow):
        proxyRigGenerator_MainWindow.setWindowTitle(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "MainWindow", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Geos", None, -1))
        self.proxyGeo_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "<Select all geometries and press Load>", None, -1))
        self.loadGeo_pushButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Load", None, -1))
        self.cutCube_groupBox.setTitle(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Cut Cube", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Replace with", None, -1))
        self.snapCube_pushButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Snap", None, -1))
        self.replaceWith_lineEdit.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "_R_", None, -1))
        self.mirrorCube_pushButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Mirror", None, -1))
        self.jntSuffix_lineEdit.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "_Jnt", None, -1))
        self.geoSuffix_lineEdit.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "_Geo", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Joint Suffix", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Geo suffix", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Search for", None, -1))
        self.searchFor_lineEdit.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "_L_", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Size", None, -1))
        self.newCube_pushButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "New", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Connect Using", None, -1))
        self.constraint_radioButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Constraint", None, -1))
        self.parent_radioButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Parent", None, -1))
        self.matrix_radioButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Matrix", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "None", None, -1))
        self.cut_pushButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Generate Proxy Geos", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.proxyCut_tab), QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Proxy", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Skin Geo", None, -1))
        self.skinGeo_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "<Select skin geo and press Load>", None, -1))
        self.skinGeo_pushButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Load", None, -1))
        self.rootJnt_pushButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Load", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Root Jnt", None, -1))
        self.rootJnt_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "<Select root joint and press Load>", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Geo Suffix", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Jnt Suffix", None, -1))
        self.generateSkinWeight_pushButton.setText(QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Generate Skin Weights", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.skinWeights_tab), QtWidgets.QApplication.translate("proxyRigGenerator_MainWindow", "Skin Weights", None, -1))

